from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from db import Artwork, SessionLocal

logger = logging.getLogger(__name__)


def _manifest_path(artwork_dir: Path, slug: str) -> Path:
    candidates = sorted(artwork_dir.glob("*-assets.json"))
    if candidates:
        return candidates[0]
    return artwork_dir / f"{slug}-assets.json"


def _cleanup_manifest_analysis(artwork_dir: Path, slug: str) -> bool:
    path = _manifest_path(artwork_dir, slug)
    if not path.exists():
        return False
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        logger.warning("Failed to parse manifest during cleanup: %s", path)
        return False

    if not isinstance(payload, dict):
        return False

    files = payload.get("files")
    if isinstance(files, dict):
        files.pop("analysis_stage1", None)
        files.pop("ai_packet", None)
        files.pop("copy_etsy", None)

    payload["analysis"] = {
        "status": "cancelled",
        "stage": "cancelled",
        "progress": 0,
        "provider": None,
        "job_id": None,
    }
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return True


def _delete_matching_artwork_record(*, slug: str, sku: str | None) -> int:
    deleted = 0
    with SessionLocal() as session:
        rows = []
        if sku:
            row = session.query(Artwork).filter(Artwork.id == sku).first()
            if row is not None:
                rows.append(row)
        if slug:
            row = session.query(Artwork).filter(Artwork.slug == slug).first()
            if row is not None and row not in rows:
                rows.append(row)

        for row in rows:
            session.delete(row)
            deleted += 1

        if deleted:
            session.commit()
    return deleted


def cleanup_analysis_job_artifacts(
    *,
    slug: str,
    sku: str | None,
    lab_roots: list[Path],
    remove_artwork_record: bool,
) -> dict[str, Any]:
    """Delete analysis output files and optionally remove related artwork DB rows."""
    deleted_files: list[str] = []
    touched_dirs: list[str] = []
    manifest_updates = 0

    # Files generated by queue worker/analysis pipeline for a slug.
    targets = {
        f"{slug}-analysis-stage1.json",
        f"{slug}-copy-etsy.json",
        f"{slug}-ai-packet.json",
        f"{slug.lower()}-listing.json",
        f"{slug.lower()}-status.json",
        "listing.json",
        "status.json",
    }

    for root in lab_roots:
        artwork_dir = root / slug
        if not artwork_dir.exists() or not artwork_dir.is_dir():
            continue

        touched_dirs.append(str(artwork_dir))
        for name in targets:
            candidate = artwork_dir / name
            if candidate.exists() and candidate.is_file():
                try:
                    candidate.unlink()
                    deleted_files.append(str(candidate))
                except Exception:
                    logger.exception("Failed deleting cleanup file: %s", candidate)

        if _cleanup_manifest_analysis(artwork_dir, slug):
            manifest_updates += 1

    artwork_rows_deleted = 0
    if remove_artwork_record:
        try:
            artwork_rows_deleted = _delete_matching_artwork_record(slug=slug, sku=sku)
        except Exception:
            logger.exception("Failed removing artwork DB row during job cleanup: slug=%s sku=%s", slug, sku)

    return {
        "slug": slug,
        "touched_dirs": touched_dirs,
        "deleted_files": deleted_files,
        "manifest_updates": manifest_updates,
        "artwork_rows_deleted": artwork_rows_deleted,
    }
